name: upcom-explorer
version: 0.1.0
authors:
- Mike Lewis <mike@updroid.com>
description: UpCom Panel for file and ROS management.
homepage: https://www.updroid.com/upcom
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  upcom-api:
    path: /home/crunchex/work/upcom-api/

